version: '3.1'

services: 
  elastic-search:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.7.1
    ports:
      - 5601:5601
    depends_on: 
      - elastic-search
    environment:
      - ELASTICSEARCH_URL=http://elastic-search:9200
      

volumes: 
  elasticsearch-data: