namespace Elastic.Commands;

/// <summary>
/// Documents are immutable. They are replaced on update
/// </summary>
public class SingleCommands
{
    private class Get
    {
        // GET /orders/_doc/1
    }

    private class Delete
    {
        // DELETE /orders/_doc/1
    }

    private class Create
    {
        // POST /orders/_doc --creates a document with autogenerated id
        // {
        //     "name" : "My Name",
        //     "price" :  69
        // }
        
        // PUT /orders/_doc/1 --creates (or replaces) a document with id = 1
        // {
        //     "name" : "My Name",
        //     "price" :  69
        // }
    }

    private class Update
    {
        // PUT /orders/_doc/1 --creates (or replaces) a document with id = 1
        // {
        //     "name" : "My Name",
        //     "price" :  69
        // }
    
        // POST /orders/_update/1 --updates (replaces) a document with id = 1
        // {
        //     "doc": {
        //         "name" : "New Value",
        //         "price" : 123
        //     }
        // }
    
        // POST /orders/_update/1 --updates (replaces a document) a specific value of a document based on a script, aka Redis LUA
        // {
        //     "script": {
        //         "source": "ctx._source.price--"
        //         "source": "ctx._source.price = 10"
        //         "source": "ctx._source.price += params.newPrice",
        //         "params": {
        //             "newPrice" : 123
        //         }
        //     }
        // }
    }
}