namespace Elastic.Common;


public class SystemCommands
{
    // http://localhost:5601/app/dev_tools#/console
    
    // system
    // GET /_cluster/health
    // GET /_cat/nodes?v
    // GET /_cat/indices?v&expand_wildcards=all
    // GET /_cat/shards?v
}

public class IndexCommands
{
    // DELETE /orders

    // PUT /orders --creates an index
    // {
    //     "settings": {
    //         "number_of_shards": 1,
    //         "number_of_replicas": 0
    //     }
    // }
}

/// <summary>
/// Documents are immutable. They are replaced on update
/// </summary>
public class DocCommands
{
    // GET /orders/_doc/1
    
    // POST /orders/_doc --creates a document with autogenerated id
    // {
    //     "name" : "My Name",
    //     "price" :  69
    // }

    // PUT /orders/_doc/1 --creates a document with id = 1
    // {
    //     "name" : "My Name",
    //     "price" :  69
    // }
    
    // POST /orders/_update/1 --updates (replaces) a document with id = 1
    // {
    //     "doc": {
    //         "name" : "New Value",
    //         "price" : 123
    //     }
    // }
    
    // POST /orders/_update/1 --updates (replaces a document) a specific value of a document based on a script, aka Redis LUA
    // {
    //     "script": {
    //         "source": "ctx._source.price--"
    //         "source": "ctx._source.price = 10"
    //         "source": "ctx._source.price += params.newPrice",
    //         "params": {
    //             "newPrice" : 123
    //         }
    //     }
    // }
}